---
abstract: DateTime-Factory
author:
  - 'takuji@senchan.jp <takuji@senchan.jp>'
build_requires:
  Test::LoadAllModules: 0.02
  Test::More: 0.96
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DateTime-Factory
provides:
  DateTime::Factory:
    file: lib/DateTime/Factory.pm
    version: 0.01
requires:
  Data::Validator: 0.05
  DateTime: 0
  DateTime::TimeZone: 0
  Mouse: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
